### ISSUE TITLE
Data Format?

### ISSUE THREAD

**Issue by croros** [adebowaledaniel/sits-change-detection#1]
Hello,

Thanks for the thorough implementation of your work.

I have one question though, I took a look at your sample data but I am confused by the format. How does the sample data represent an image?
I know you took inspiration from here: https://github.com/VSainteuf/pytorch-psetae#data-format
which uses  TxCxS (# of temporal observations x # of channels x # of pixels), but each sample is 53 x 10. 

Correct me if I'm wrong, but I assume there's 10 channels and 53 temporal observations. Does each sample represent a pixel in an image?

**Comment by adebowaledaniel** [comment]
Hey @croros 

Thanks for reaching out. You are right; each sample does represent a pixel in an image as Temporal observation x Channels (53x10). The article is [here](https://ieeexplore.ieee.org/document/10281594)* for further reading, and [poster presentation](https://adebowaledaniel.com/doc/IGARSS_2023_Poster_presentation.pdf) here. 

_*I can also share it with you if you can't access it._
